### ISSUE TITLE
Make PriceAware.sol an inheritable "library" contract

### ISSUE THREAD

**Issue by DaigaroCota** [redstone-finance/redstone-evm-connector#19]
Using Openzeppelin as a good reference, I suggest to make the architecture of PriceAware.sol, more like an inheritable contract. 

At the moment, the import and inheritance of Ownable.sol, may be in conflict with children contract that already have their own implementation of Ownable.sol.

Suggest that most functions must be internal, and virtual. 

Allow end user to decide access control by overriding if desired. 

https://github.com/redstone-finance/redstone-evm-connector/blob/35d81e2d9fe3099b543fba9323ac79bddcb4ff49/contracts/message-based/PriceAware.sol#L6

**Comment by jakub-wojciechowski** [comment]
Hey @DaigaroCota, thank you for the comment. 
It makes total sense.
We've also heard similar feedback regarding using the OwnableUpgradable pattern. 

We'll try to refactor the code to keep the simplest and most basic abstract version of the PriceAware to offer more flexibility for the users. 

Thank you for the feedback and a great suggestion !!!

**Comment by hatskier** [comment]
Hey @DaigaroCota! Thank you again for this great idea. I've recently applied this change and made the signer and timestamp verification logic more flexible. Can you please take a look (https://github.com/redstone-finance/redstone-evm-connector/blob/master/contracts/message-based/PriceAware.sol) and close the issue if you don't see problems with the new approach?
