### ISSUE TITLE
Return wrapped contracts as promise

### ISSUE THREAD

**Issue by 0xnook** [redstone-finance/redstone-evm-connector#22]
Hello, I upped the version of your library from 1.3.8 to 2.1.2, and noticed that calling `WrapperBuilder.wrapLite(someContract).usingPriceFeed('redstone-stocks')` takes longer than before (I assume this is due to the streamr subscriptions) and blocks the whole JS UI im building until they load (I wrap 3 contracts simultaneously). 

Is there any way this can be done in a snappier way? Perhaps by having a method the returns of the wrapped contracts as a promise.

**Comment by hatskier** [comment]
Hey @0xnook thank you for creating this issue. We definitely need to fix it ASAP. Unfortunately, it would be difficult to change it to Promise because we don't call any async operations in the `wrapLite` method. But I will be happy to analyze the performance issues and fix them. Can you please share your code so I can try to reproduce the problem?

**Comment by 0xnook** [comment]
Hey @hatskier, the project I'm working on is going to be open sourced soon, but not yet! (a bit self conscious about my code, prefer to ship something more ready hehe). 

In the meantime I created this repo with a minimal example https://github.com/0xnook/wrapperTest, where clicking the button wraps 2 contracts using the evm-connector, and a 1s increment counter is shown to showcase the blocking behavior.

Thank you so much for taking a look!

**Comment by hatskier** [comment]
@0xnook I've found the exact reason of the issue. Will fix it during next 2-3 days and let you know :)

**Comment by 0xnook** [comment]
Awesome guys, thanks for the fix and hope we can continue working together!

Our frontend is now open source, and hope it can serve as a reference implementation of your library https://github.com/PipilaDAO/frontend

**Comment by 0xnook** [comment]
Can confirm the new changes work like a charm and performance issues are fixed :smile:
